default:
  golem_name: dummyGolem
  golem_version: 0.0.0.9000
  app_prod: no
  uid: !expr Sys.getenv("dashboard_uid")
  pwd: !expr Sys.getenv("dashboard_pwd")
production:
  app_prod: yes
  uid: "production_user"
  pwd: !expr Sys.getenv("DB_PWD")
dev:
  golem_wd: !expr here::here()
